/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package strategypattern;

import strategypattern.StrategyPatternImpl.IMounted;
import strategypattern.StrategyPatternImpl.OnFoot;
import strategypattern.StrategyPatternImpl.Player;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Halit Burak Yeşildal 18050111043
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    
    
    Player paladin;

    public Frame() {
        initComponents();
        damageTextArea.setLineWrap(true);
        paladin = new Player(100.0);
        damageTextArea.setText("  You're on foot.\n  Damage is :" + Double.toString(paladin.applyMounted(new OnFoot())));
        ImageIcon onFootIcon = new ImageIcon(new ImageIcon(getClass().getResource("/strategypattern/icons/onFoot.png")).getImage().getScaledInstance(188, 245, Image.SCALE_DEFAULT));
        photoLabel.setIcon(onFootIcon);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        onFootButton = new javax.swing.JButton();
        onHorseButton = new javax.swing.JButton();
        photoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        damageTextArea = new javax.swing.JTextArea();
        onDragonButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("War of Paladin");

        onFootButton.setText("On Foot");
        onFootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onFootButtonActionPerformed(evt);
            }
        });

        onHorseButton.setText("On Horse");
        onHorseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onHorseButtonActionPerformed(evt);
            }
        });

        damageTextArea.setColumns(20);
        damageTextArea.setRows(5);
        jScrollPane1.setViewportView(damageTextArea);

        onDragonButton.setText("On Dragon");
        onDragonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDragonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(onFootButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onHorseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onDragonButton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(onFootButton)
                        .addGap(18, 18, 18)
                        .addComponent(onHorseButton)
                        .addGap(18, 18, 18)
                        .addComponent(onDragonButton)))
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onFootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFootButtonActionPerformed
        // TODO add your handling code here:
        IMounted mounted = paladin.getMyMount(1);
        paladin.applyMounted(mounted);
        ImageIcon onFootIcon = new ImageIcon(new ImageIcon(getClass().getResource("/strategypattern/icons/onFoot.png")).getImage().getScaledInstance(188, 245, Image.SCALE_DEFAULT));
        photoLabel.setIcon(onFootIcon);
        damageTextArea.setText("  You're on foot.\n  Damage is :" + Double.toString(paladin.applyMounted(mounted)));
        //Todo: set picture and damage;

    }//GEN-LAST:event_onFootButtonActionPerformed

    private void onHorseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onHorseButtonActionPerformed
        // TODO add your handling code here:
        IMounted mounted = paladin.getMyMount(2);

        ImageIcon onHorseIcon = new ImageIcon(new ImageIcon(getClass().getResource("/strategypattern/icons/onHorse.png")).getImage().getScaledInstance(188, 245, Image.SCALE_DEFAULT));
        photoLabel.setIcon(onHorseIcon);
        damageTextArea.setText("  You're on horse.\n  Damage is :" + Double.toString(paladin.applyMounted(mounted)));
        //Todo set picture and damage;
    }//GEN-LAST:event_onHorseButtonActionPerformed

    private void onDragonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDragonButtonActionPerformed
        // TODO add your handling code here:
        IMounted mounted = paladin.getMyMount(3);
        paladin.applyMounted(mounted);
        ImageIcon onDragonIcon = new ImageIcon(new ImageIcon(getClass().getResource("/strategypattern/icons/onDragon.png")).getImage().getScaledInstance(188, 245, Image.SCALE_DEFAULT));
        photoLabel.setIcon(onDragonIcon);
        damageTextArea.setText("  You're on dragon.\n  Damage is :" + Double.toString(paladin.applyMounted(mounted)));
        //Todo: set picture and damage;
    }//GEN-LAST:event_onDragonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea damageTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton onDragonButton;
    private javax.swing.JButton onFootButton;
    private javax.swing.JButton onHorseButton;
    private javax.swing.JLabel photoLabel;
    // End of variables declaration//GEN-END:variables
}
