package observerpattern;

import java.awt.Image;
import javax.swing.ImageIcon;

import static javax.swing.JOptionPane.showMessageDialog;

import observerpattern.OberserverPatternImpl.Devices.*;
import observerpattern.OberserverPatternImpl.Server;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author Halit Burak Yeşildal 18050111043
 */
public class Frame extends javax.swing.JFrame {

    Server server;
    Phone phone;
    Tablet tablet;
    TV tv;

    public Frame() {

        initComponents();

        server = new Server();
        phone = new Phone(server, this.phoneTextArea);
        tablet = new Tablet(server, this.tabletTextArea);
        tv = new TV(server, this.tvTextArea);
        
        ImageIcon phoneIcon = new ImageIcon(new ImageIcon(getClass().getResource("/observerpattern/icons/phone.png")).getImage().getScaledInstance(70, 120, Image.SCALE_DEFAULT));
        ImageIcon tabletIcon = new ImageIcon(new ImageIcon(getClass().getResource("/observerpattern/icons/tablet.png")).getImage().getScaledInstance(70, 120, Image.SCALE_DEFAULT));
        ImageIcon tvIcon = new ImageIcon(new ImageIcon(getClass().getResource("/observerpattern/icons/tv.png")).getImage().getScaledInstance(70, 120, Image.SCALE_DEFAULT));

        phoneLabel.setIcon(phoneIcon);
        tabletLabel.setIcon(tabletIcon);
        tvLabel.setIcon(tvIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serverPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        inputBoxServer = new javax.swing.JTextField();
        sendMessageButton = new javax.swing.JButton();
        phonePane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        phoneTextArea = new javax.swing.JTextArea();
        phoneLabel = new javax.swing.JLabel();
        tabletPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabletTextArea = new javax.swing.JTextArea();
        tabletLabel = new javax.swing.JLabel();
        tvPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tvTextArea = new javax.swing.JTextArea();
        tvLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Info Service");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        inputBoxServer.setToolTipText("Enter input");
        inputBoxServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBoxServerActionPerformed(evt);
            }
        });

        sendMessageButton.setText("Send Message");
        sendMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendMessageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(inputBoxServer)
                                        .addComponent(sendMessageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(inputBoxServer, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addGap(51, 51, 51)
                                .addComponent(sendMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
        );

        serverPane.addTab("Server", jPanel1);

        phoneTextArea.setColumns(20);
        phoneTextArea.setRows(5);
        jScrollPane1.setViewportView(phoneTextArea);

        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneLabel.setToolTipText("");

        javax.swing.GroupLayout phonePaneLayout = new javax.swing.GroupLayout(phonePane);
        phonePane.setLayout(phonePaneLayout);
        phonePaneLayout.setHorizontalGroup(
                phonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                        .addGroup(phonePaneLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(phoneLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        phonePaneLayout.setVerticalGroup(
                phonePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(phonePaneLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(phoneLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        serverPane.addTab("Phone", phonePane);

        tabletTextArea.setColumns(20);
        tabletTextArea.setRows(5);
        jScrollPane2.setViewportView(tabletTextArea);

        tabletLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout tabletPaneLayout = new javax.swing.GroupLayout(tabletPane);
        tabletPane.setLayout(tabletPaneLayout);
        tabletPaneLayout.setHorizontalGroup(
                tabletPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabletPaneLayout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(tabletLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        tabletPaneLayout.setVerticalGroup(
                tabletPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tabletPaneLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(tabletLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        serverPane.addTab("Tablet", tabletPane);

        tvTextArea.setColumns(20);
        tvTextArea.setRows(5);
        jScrollPane3.setViewportView(tvTextArea);

        tvLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout tvPaneLayout = new javax.swing.GroupLayout(tvPane);
        tvPane.setLayout(tvPaneLayout);
        tvPaneLayout.setHorizontalGroup(
                tvPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tvPaneLayout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(tvLabel)
                                .addContainerGap(230, Short.MAX_VALUE))
                        .addComponent(jScrollPane3)
        );
        tvPaneLayout.setVerticalGroup(
                tvPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tvPaneLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(tvLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        serverPane.addTab("TV", tvPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(serverPane)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(serverPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputBoxServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBoxServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBoxServerActionPerformed

    private void sendMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendMessageButtonActionPerformed
        // TODO add your handling code here:
        String input = inputBoxServer.getText().length() > 0 ? inputBoxServer.getText() : "Test";
        server.notifyObservers(input);
        showMessageDialog(null, "Message has been sent!");

    }//GEN-LAST:event_sendMessageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Frame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputBoxServer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JPanel phonePane;
    private javax.swing.JTextArea phoneTextArea;
    private javax.swing.JButton sendMessageButton;
    private javax.swing.JTabbedPane serverPane;
    private javax.swing.JLabel tabletLabel;
    private javax.swing.JPanel tabletPane;
    private javax.swing.JTextArea tabletTextArea;
    private javax.swing.JLabel tvLabel;
    private javax.swing.JPanel tvPane;
    private javax.swing.JTextArea tvTextArea;
    // End of variables declaration//GEN-END:variables
}
