/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package decoratorpattern;

import decoratorpattern.DecoraterPattern.BusinessTicket;
import decoratorpattern.DecoraterPattern.EconomyTicket;
import decoratorpattern.DecoraterPattern.ExtraLugWeigth;
import decoratorpattern.DecoraterPattern.FligthTicket;
import decoratorpattern.DecoraterPattern.InternetConnectionTicket;
import decoratorpattern.DecoraterPattern.Meal;
import decoratorpattern.DecoraterPattern.WindowEdgeTicket;
import java.awt.Image;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;

/**
 *
 * @author 18050111043 Halit Burak Yeşildal
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public FligthTicket ticket;
    List<JCheckBox> list;

    public FligthTicket optionalStuffs(JCheckBox box, FligthTicket ticket) {

        switch (box.getActionCommand()) {
            case "meal":
                ticket = new Meal(ticket);
                break;
            case "window":
                ticket = new WindowEdgeTicket(ticket);
                break;
            case "internet":
                ticket = new InternetConnectionTicket(ticket);
                break;
            case "extra":
                ticket = new ExtraLugWeigth(ticket);
                break;
            default:
                ticket = null;
                break;
        }

        return ticket;

    }

    public Frame() {
        initComponents();
        textArea.setLineWrap(true);

        businessTicketRadio.setActionCommand("businessTicket");
        economyTicketRadio.setActionCommand("economyTicket");

        mealCB.setActionCommand("meal");
        windowEdgeCB.setActionCommand("window");
        internetConnectionCB.setActionCommand("internet");
        extraLugWeightCB.setActionCommand("extra");

        list = new ArrayList<>();
        list.add(mealCB);
        list.add(windowEdgeCB);
        list.add(internetConnectionCB);
        list.add(extraLugWeightCB);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ticketRadioButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        businessTicketRadio = new javax.swing.JRadioButton();
        economyTicketRadio = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        extraLugWeightCB = new javax.swing.JCheckBox();
        mealCB = new javax.swing.JCheckBox();
        windowEdgeCB = new javax.swing.JCheckBox();
        internetConnectionCB = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        iconLabel = new javax.swing.JLabel();
        buyTicketButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Get Ticket");

        ticketRadioButtonGroup.add(businessTicketRadio);
        businessTicketRadio.setSelected(true);
        businessTicketRadio.setText("Business Ticket");

        ticketRadioButtonGroup.add(economyTicketRadio);
        economyTicketRadio.setText("Economy Ticket");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(businessTicketRadio)
                    .addComponent(economyTicketRadio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(businessTicketRadio)
                .addGap(18, 18, 18)
                .addComponent(economyTicketRadio)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        extraLugWeightCB.setText("Extra Lug Weight");

        mealCB.setText("Meal");

        windowEdgeCB.setText("Window Edge");

        internetConnectionCB.setText("Internet Connection");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extraLugWeightCB)
                    .addComponent(internetConnectionCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mealCB)
                    .addComponent(windowEdgeCB))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extraLugWeightCB)
                    .addComponent(windowEdgeCB))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(internetConnectionCB)
                    .addComponent(mealCB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        buyTicketButton.setText("Buy Ticket");
        buyTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTicketButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(buyTicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buyTicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buyTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTicketButtonActionPerformed
        // TODO add your handling code here:
        ticket = ticketRadioButtonGroup.getSelection().getActionCommand().equals("businessTicket") ? new BusinessTicket() : new EconomyTicket();
        //ImageIcon onFootIcon = new ImageIcon(new ImageIcon(getClass().getResource("/strategypattern/icons/onFoot.png")).getImage().getScaledInstance(188, 245, Image.SCALE_DEFAULT));
        URL url = ticketRadioButtonGroup.getSelection().getActionCommand().equals("businessTicket") ? getClass().getResource("/decoratorpattern/icons/business.png") : getClass().getResource("/decoratorpattern/icons/economy.png");
        ImageIcon img = new ImageIcon(new ImageIcon(url).getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT));
        iconLabel.setIcon(img);

        for (JCheckBox c : list) {
            if (c.isSelected()) {
                ticket = optionalStuffs(c, ticket);
            }
        }

        textArea.setText(ticket.getDescription() + ticket.cost());


    }//GEN-LAST:event_buyTicketButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton businessTicketRadio;
    private javax.swing.JButton buyTicketButton;
    private javax.swing.JRadioButton economyTicketRadio;
    private javax.swing.JCheckBox extraLugWeightCB;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JCheckBox internetConnectionCB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mealCB;
    private javax.swing.JTextArea textArea;
    private javax.swing.ButtonGroup ticketRadioButtonGroup;
    private javax.swing.JCheckBox windowEdgeCB;
    // End of variables declaration//GEN-END:variables
}
